export const SET_COUNTRY = "SET_COUNTRY";
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';
export const SEARCH_NEWS_REQUEST = "SEARCH_NEWS_REQUEST";
export const SEARCH_NEWS_SUCCESS = "SEARCH_NEWS_SUCCESS";
export const SEARCH_NEWS_FAILURE = "SEARCH_NEWS_FAILURE";
export const RESET_SEARCH = "RESET_SEARCH";